// Motion One presets — generated by designlang (motionlang)
// Source: https://linear.app
// 2026-07-02T08:24:30.747Z
//
//   import { animate } from 'motion';
//   import { animations, easings, durations } from './linear.app-motion.one.js';
//
//   animations.fadeIn('#hero');
//   animations.slideUp('.card', { delay: 0.1 });

/** Easing curves extracted from the live page, as Motion One cubic-bezier arrays. */
export const easings = {
  easeOut: [0.25, 0.46, 0.45, 0.94], // 83× on page
  easeInOut: [0.25, 0.1, 0.25, 1], // 25× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  xs: 0.1,
  sm: 0.16,
  md: 0.4,
};

/** Motion One spring options — pass as the `type: 'spring'` block of an animate() call. */
export const springs = {
  soft: { type: 'spring', stiffness: 320, damping: 30, mass: 1 },
};

/** @keyframes blocks reconstructed as Motion One keyframe maps. */
export const keyframes = {
  gridDot00UpDown: {
    "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3"]
  },
  gridDot01UpDown: {
    "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","1","1","0.3","0.3","0.3","0.3","1","1","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3"]
  },
  gridDot02UpDown: {
    "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0.3","0.3","0.3","0.3","0.3","0.3"]
  },
  gridDot03UpDown: {
    "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","1","1","0.3","0.3","0.3","0.3","1","1","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3"]
  },
  gridDot04UpDown: {
    "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3"]
  },
  gridDot10UpDown: {
    "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3"]
  },
  gridDot11UpDown: {
    "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","1","1","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","1","1","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3"]
  },
  gridDot12UpDown: {
    "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","1","1","1","1","1","1","1","1","0.3","0.3","1","1","1","1","1","1","1","1","0.3","0.3","0.3","0.3"]
  },
  gridDot13UpDown: {
    "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","1","1","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","1","1","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3"]
  },
  gridDot14UpDown: {
    "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3"]
  },
  gridDot20UpDown: {
    "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3"]
  },
  gridDot21UpDown: {
    "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","1","1","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","1","1","0.3","0.3","0.3","0.3","0.3","0.3"]
  },
  gridDot22UpDown: {
    "opacity": ["0.3","0.3","0.3","0.3","1","1","1","1","1","1","1","1","0.3","0.3","0.3","0.3","0.3","0.3","1","1","1","1","1","1","1","1","0.3","0.3"]
  },
  gridDot23UpDown: {
    "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","1","1","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","1","1","0.3","0.3","0.3","0.3","0.3","0.3"]
  },
  gridDot24UpDown: {
    "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3"]
  },
  gridDot30UpDown: {
    "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3"]
  },
};

/** Animate-on-call helpers. Each takes a Motion One target + optional override. */
import { animate } from 'motion';

const _t = { duration: 0.4, easing: easings.easeOut };

export const animations = {
  fadeIn: (target, opts = {}) =>
    animate(target, { opacity: [0, 1] }, { ..._t, ...opts }),
  fadeOut: (target, opts = {}) =>
    animate(target, { opacity: [1, 0] }, { ..._t, ...opts }),
  slideUp: (target, opts = {}) =>
    animate(target, { opacity: [0, 1], y: [16, 0] }, { ..._t, ...opts }),
  slideDown: (target, opts = {}) =>
    animate(target, { opacity: [0, 1], y: [-16, 0] }, { ..._t, ...opts }),
  scaleIn: (target, opts = {}) =>
    animate(target, { opacity: [0, 1], scale: [0.96, 1] }, { ..._t, ...opts }),
  pop: (target, opts = {}) =>
    animate(target, { scale: [0.9, 1] }, { ...springs.soft, ...opts }),
};

/** Site uses scroll- or view-timeline. Helpers wired to Motion One's `inView` / `scroll`. */
import { inView, scroll } from 'motion';

export const enterOnView = (target, variant = animations.slideUp) =>
  inView(target, (el) => { variant(el.target); });

export const parallaxY = (target, distance = 80) =>
  scroll(animate(target, { y: [0, -distance] }, { easing: 'linear' }));

export default { easings, durations, springs, keyframes, animations };
