// Framer Motion presets — generated by designlang (motionlang)
// Source: https://linear.app
// 2026-07-02T08:24:30.746Z
//
//   import { transitions, variants } from './linear.app-motion.framer';
//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"
//               transition={transitions.base} />

/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */
export const easings = {
  easeOut: [0.25, 0.46, 0.45, 0.94], // 83× on page
  easeInOut: [0.25, 0.1, 0.25, 1], // 25× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  xs: 0.1,
  sm: 0.16,
  md: 0.4,
};

/** Spring presets — pass to a Framer Motion `transition` prop. */
export const springs = {
  soft: { type: 'spring', stiffness: 320, damping: 30, mass: 1 },
};

/** Ready-to-spread Framer Motion transition objects. */
export const transitions = {
  base:  { duration: 0.4, ease: easings.easeOut },
  fast:  { duration: 0.200, ease: easings.easeOut },
  slow:  { duration: 0.720, ease: easings.easeOut },
  spring: springs.soft,
};

/** Common variants wired to the extracted timing. */
export const variants = {
  fade: {
    hidden: { opacity: 0 },
    show:   { opacity: 1, transition: transitions.base },
  },
  slideUp: {
    hidden: { opacity: 0, y: 16 },
    show:   { opacity: 1, y: 0, transition: transitions.base },
  },
  scaleIn: {
    hidden: { opacity: 0, scale: 0.96 },
    show:   { opacity: 1, scale: 1, transition: transitions.base },
  },
  pop: {
    hidden: { opacity: 0, scale: 0.9 },
    show:   { opacity: 1, scale: 1, transition: springs.soft },
  },
  stagger: {
    hidden: {},
    show:   { transition: { staggerChildren: 0.100 } },
  },
  gridDot00UpDown: {
    hidden: {},
    show: {
      "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3"],
      transition: transitions.base,
    },
  },
  gridDot01UpDown: {
    hidden: {},
    show: {
      "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","1","1","0.3","0.3","0.3","0.3","1","1","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3"],
      transition: transitions.base,
    },
  },
  gridDot02UpDown: {
    hidden: {},
    show: {
      "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","1","1","1","1","1","1","1","1","1","1","1","1","1","1","0.3","0.3","0.3","0.3","0.3","0.3"],
      transition: transitions.base,
    },
  },
  gridDot03UpDown: {
    hidden: {},
    show: {
      "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","1","1","0.3","0.3","0.3","0.3","1","1","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3"],
      transition: transitions.base,
    },
  },
  gridDot04UpDown: {
    hidden: {},
    show: {
      "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3"],
      transition: transitions.base,
    },
  },
  gridDot10UpDown: {
    hidden: {},
    show: {
      "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3"],
      transition: transitions.base,
    },
  },
  gridDot11UpDown: {
    hidden: {},
    show: {
      "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","1","1","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3","1","1","0.3","0.3","0.3","0.3","0.3","0.3","0.3","0.3"],
      transition: transitions.base,
    },
  },
  gridDot12UpDown: {
    hidden: {},
    show: {
      "opacity": ["0.3","0.3","0.3","0.3","0.3","0.3","1","1","1","1","1","1","1","1","0.3","0.3","1","1","1","1","1","1","1","1","0.3","0.3","0.3","0.3"],
      transition: transitions.base,
    },
  },
};

/** Site uses scroll- or view-timeline. Drop-in `whileInView` props. */
export const inView = {
  fadeIn: {
    initial: variants.fade.hidden,
    whileInView: variants.fade.show,
    viewport: { once: true, amount: 0.3 },
  },
  riseIn: {
    initial: variants.slideUp.hidden,
    whileInView: variants.slideUp.show,
    viewport: { once: true, amount: 0.3 },
  },
};

export default { easings, durations, springs, transitions, variants, inView };
