// Web Animations API presets — generated by designlang (motionlang)
// Source: https://vercel.com
// 2026-07-02T04:43:51.973Z
//
// Zero-dependency. Runs on the browser-native Element.animate().
//   import { animations } from './vercel.com-motion.waapi.js';
//   animations.fadeIn(document.querySelector('#hero'));
//   await animations.slideUp(card, { delay: 80 }).finished;

/** Easing curves extracted from the live page, as WAAPI easing strings. */
export const easings = {
  custom1: 'cubic-bezier(0.4, 0, 0.2, 1)', // 144× on page
  easeOut: 'cubic-bezier(0, 0, 0.2, 1)', // 12× on page
  linear: 'linear', // 2× on page
};

/** Duration presets (milliseconds), extracted from the live page. */
export const durations = {
  xs: 100,
  sm: 200,
  md: 300,
  lg: 500,
  xl: 1000,
};

/** @keyframes blocks reconstructed as WAAPI keyframe arrays. */
export const keyframes = {
  fadeIn: [{"opacity":"0","offset":0},{"opacity":"1","offset":1}],
  marquee: [{"transform":"translate(0px)","offset":0},{"transform":"translateX(calc(-100% - var(--marquee-gap)))","offset":1}],
};

/** Honours the user's reduced-motion preference. */
export const prefersReducedMotion = () =>
  typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches;

const _timing = { duration: 300, easing: easings.custom1, fill: 'both' };

function _animate(el, frames, opts = {}) {
  const timing = { ..._timing, ...opts };
  if (prefersReducedMotion()) timing.duration = 0;
  return el.animate(frames, timing);
}

/** Animate-on-call helpers. Each returns the live Animation (await `.finished`). */
export const animations = {
  fadeIn: (el, opts = {}) => _animate(el, [{ opacity: 0 }, { opacity: 1 }], opts),
  fadeOut: (el, opts = {}) => _animate(el, [{ opacity: 1 }, { opacity: 0 }], opts),
  slideUp: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'translateY(16px)' }, { opacity: 1, transform: 'translateY(0)' }], opts),
  slideDown: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'translateY(-16px)' }, { opacity: 1, transform: 'translateY(0)' }], opts),
  scaleIn: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'scale(0.96)' }, { opacity: 1, transform: 'scale(1)' }], opts),
};

export default { easings, durations, keyframes, animations, prefersReducedMotion };
