// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://vercel.com
// Generated: 2026-07-02T04:43:51.970Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary';
export type ColorHex  = '#ebebeb' | '#171717' | '#4d4d4d' | '#666666' | '#ffffff' | '#8f8f8f' | '#a8a8a8' | '#000000' | '#0070f3' | '#7d7d7d' | '#383838';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'GeistSans' | 'Geist Mono';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '600' | '450';

export type SpacingToken = '1px' | '32px' | '40px' | '64px' | '80px' | '208px' | '256px' | '276px';

export type RadiusToken = '2px' | '6px' | '12px';

export type DurationToken = '100ms' | '200ms' | '300ms' | '500ms' | '1000ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
