// GSAP presets — generated by designlang (motionlang)
// Source: https://vercel.com
// 2026-07-02T04:43:51.973Z
//
//   import gsap from 'gsap';
//   import { registerEases, reveals } from './vercel.com-motion.gsap.js';
//   registerEases(gsap);            // one-time: registers CustomEases
//   reveals.slideUp('.card');

/** CustomEase path data extracted from the live page, keyed by family. */
export const eases = {
  custom1: 'M0,0 C0.4,0 0.2,1 1,1', // 144× on page
  easeOut: 'M0,0 C0,0 0.2,1 1,1', // 12× on page
  linear: 'M0,0 C0,0 1,1 1,1', // 2× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  xs: 0.1,
  sm: 0.2,
  md: 0.3,
  lg: 0.5,
  xl: 1,
};

/** Register every extracted curve as a named GSAP CustomEase. Call once. */
export function registerEases(gsap) {
  const CustomEase = gsap.plugins?.CustomEase || (typeof window !== 'undefined' && window.CustomEase);
  if (!CustomEase) {
    console.warn('[motion.gsap] CustomEase plugin not registered — call gsap.registerPlugin(CustomEase) first.');
    return;
  }
  for (const [name, path] of Object.entries(eases)) CustomEase.create(name, path);
}

/** gsap.from() reveal helpers. Pass any GSAP target + optional vars override. */
export const reveals = {
  fadeIn: (target, vars = {}) => gsap.from(target, { opacity: 0, duration: 0.3, ease: 'custom1', ...vars }),
  slideUp: (target, vars = {}) => gsap.from(target, { opacity: 0, y: 24, duration: 0.3, ease: 'custom1', ...vars }),
  slideDown: (target, vars = {}) => gsap.from(target, { opacity: 0, y: -24, duration: 0.3, ease: 'custom1', ...vars }),
  scaleIn: (target, vars = {}) => gsap.from(target, { opacity: 0, scale: 0.96, duration: 0.3, ease: 'custom1', ...vars }),
  pop: (target, vars = {}) => gsap.from(target, { scale: 0.9, duration: 0.3, ease: 'custom1', ...vars }),
};

/** Site uses scroll-/view-timeline. Batch-reveals elements as they enter. */
/** Requires: gsap.registerPlugin(ScrollTrigger). */
export function revealOnScroll(targets, vars = {}) {
  return gsap.utils.toArray(targets).map((el) =>
    gsap.from(el, {
      opacity: 0, y: 24, duration: 0.3, ease: 'custom1', ...vars,
      scrollTrigger: { trigger: el, start: 'top 85%', toggleActions: 'play none none reverse' },
    }));
}

export default { eases, durations, registerEases, reveals };
