server {
    listen 80;
    listen [::]:80;
    server_name video-notes-8-135-44-86.sslip.io;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 302 /next;
    }
}
